hansemannn/titanium-firebase-cloud-messaging

README.md, android/timodule.xml
User can place the default icon at the proper platform/android/res/drawable-* folders and it will be chosen for all fcm notifications as per https://firebase.google.com/docs/cloud-messaging/android/client
=> Default Icon

README.md, android/manifest, android/src/firebase/cloudmessaging/CloudMessagingModule.java, android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java
Bugfix and Readme update:
* set a default icon if none is provided (https://github.com/hansemannn/titanium-firebase-cloud-messaging/issues/28)
* added a try/catch around onTokenRefresh (https://github.com/hansemannn/titanium-firebase-cloud-messaging/issues/29)
* added explanation for `lastData`
* changed the `notificationicon` part in the README
Version 1.3.1
Testversion: https://github.com/hansemannn/titanium-firebase-cloud-messaging/releases/download/untagged-3ab96f30fd16cfa444c7/firebase.cloudmessaging-android-1.3.1.zip
(I've added a draft release)
=> Android: Default icon, try/catch for tokenrefresh, README

README.md, android/manifest, android/src/firebase/cloudmessaging/CloudMessagingModule.java, android/src/firebase/cloudmessaging/PushHandlerActivity.java, android/src/firebase/cloudmessaging/TiFirebaseInstanceIDService.java, android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java
As mentioned here: https://github.com/hansemannn/titanium-firebase-cloud-messaging/issues/35
* adding the possibility to specify a channelId in the push notification and use it in the builder
* tweaked `lastData` if app is open in background and sending a data only notification
* null check in `onTokenRefresh`
=> Android: Bugfix for Oreo notifications

android/src/firebase/cloudmessaging/CloudMessagingModule.java
Solves #47 
It seems to work correctly with data messages.
Test PHP code:
```php
<?php $url = 'https://fcm.googleapis.com/fcm/send';
$fields = array (
'to' => "<FCM TOKEN>",
'data' => array(
"test1" => "value1",
"test2" => "value2",
"timestamp"=>date('Y-m-d G:i:s'),
"title" => "title",
"message" => "message",
"big_text"=>"big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text ",
"big_text_summary"=>"big_text_summary",
"icon" => "http://via.placeholder.com/150x150",
"image" => "http://via.placeholder.com/350x150", …
```
=> Parsing boot intent notification data as a JSON object

android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java
This PR fixes a bug that prevents data notifications from being shown with the app closed or in background, when sending the `force_show_in_foreground` parameter as false.
Push notification test code:
```php
<?php $url = 'https://fcm.googleapis.com/fcm/send';
$fields = array (
'to' => "<FCM TOKEN>",
'data' => array(
"test1" => "value1",
"test2" => "value2",
"timestamp"=>date('Y-m-d G:i:s'),
"title" => "title",
"message" => "message",
"big_text"=>"big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text ", …
```
=> Fixed force_show_in_foreground parameter when set to false

README.md, android/manifest, android/src/firebase/cloudmessaging/CloudMessagingModule.java, android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java, android/timodule.xml
https://github.com/hansemannn/titanium-firebase-cloud-messaging/issues/56
Release notes:
* enable vibration with `vibrate` in the data part
* custom sounds work
* priority can be set with `priority` in the data part
* if there is an `alert` field (e.g. OneSignal) it will be used as a message
* set default playservices to `11.0.40`
* added `setNotificationChannel()` so you can create the channel with `Ti.Android.NotificationManager.createNotificationChannel()`
* added `setForceShowInForeground()` to set the forceShowInForeground inside the app instead of the push.
Testversion: [firebase.cloudmessaging-android-1.5.0.zip](http://migaweb.de/firebase.cloudmessaging-android-1.5.0.zip)
=> Android: enable default vibration, fix sounds

README.md
better differentiate between custom `notification message` and `data message` icon
=> Readme: Clearify the Android icon part

example/app.js
Topic subscription was broken on IOS. When moving the inclusion (initialisation) of the require of te firebase.cloudmessaging module below the core.configure() statement, it does work correct.
=> Moved module requirement below core.configure - fixes #65

README.md, android/manifest, android/src/firebase/cloudmessaging/CloudMessagingModule.java, android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java, android/src/firebase/cloudmessaging/Utils.java
Added `getCircleBitmap()` method in _Utils.java_ and added a check for the `icon_as_circle` parameter in _TiFirebaseMessagingService.java_
There could be done more to smoothen the border of the circular Bitmap as it might appear a bit pixelated for some images: [smooth canvas shapes with anti-aliasing](https://medium.com/@ali.muzaffar/android-why-your-canvas-shapes-arent-smooth-aa2a3f450eb5)
=> Android: Circular Icon in notification

README.md, android/src/firebase/cloudmessaging/CloudMessagingModule.java, android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java
* don't show an error when sending an empty sound (#88)
* add `error` event for Android 
* Update Readme (installation notes, XML part, clean up bullet points)
* clang files
(includes #70, so merge that first)
[Android binary 2.0.3](http://migaweb.de/firebase.cloudmessaging-android-2.0.3.zip)
=> Android: Handle empty sounds, error event, Readme update, clang

android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java
According to https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#notificationcompat.builder_2 the constructor without channelID is deprecated so using the new one in > Android.O
also changing an error log to a warning since there is a fallback for the icons and the error is misleading
=> Android: Change deprecated constructor

README.md, android/manifest, android/src/firebase/cloudmessaging/CloudMessagingModule.java, android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java, android/src/firebase/cloudmessaging/Utils.java
I use custom push sounds in my application and therefore create different notification channels for each sound. On Android Q, I am encountering the following  [documented problem](https://issuetracker.google.com/issues/131303134) when my app upgrades. I have tried the solution documented [here](https://monzo.com/blog/2019/05/28/fixing-notifications-on-android]) but it doesn’t actually fix my problem due to the fact that when you [delete notification channels](https://developer.android.com/reference/android/app/NotificationManager.html#deleteNotificationChannel(java.lang.String)) and recreate them with the same id, it uses the same sound settings it had before it was deleted. So in the current released version of my app, the sound uri’s are based on the fragile resource ids since I use …
=> Notification Channel sound uri should not be based on fragile resource ids

README.md, android/manifest, android/src/firebase/cloudmessaging/CloudMessagingModule.java, android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java
More reliable way to use lastData on Android: using shared preferences to store the data when they arrive and read them out when calling lastData
```
var win = Ti.UI.createWindow({});
var fc = require('firebase.core');
var fcm = require('firebase.cloudmessaging');
fc.configure();
fcm.createNotificationChannel({
channelId: 'default',
channelName: 'default',
sound: 'notification',
importance: 'high',
vibrate: true,
lights: true,
showBadge: true
});
fcm.addEventListener("didRefreshRegistrationToken", onToken);
fcm.addEventListener("didReceiveMessage", onMessage);
fcm.registerForPushNotifications();
console.log('FCM-Token: ' + fcm.fcmToken);
function onToken(e) {
console.log(e.fcmToken);
}
function onMessage(e) {
console.log("Got message: " + JSON.stringify(e.message));
alert("Got message: " …
```
=> Android: use SharedPrefs for lastData

android/build.gradle, android/manifest, android/src/firebase/cloudmessaging/CloudMessagingModule.java, android/src/firebase/cloudmessaging/PushHandlerActivity.java, android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java
Fixes an issue where the app crashes on the first launch after the install by performing proper null-checks on the instance instead of forcing to re-instantiate the module.
Also bumps the version of `firebase-messaging` to `20.1.6`.
[firebase.cloudmessaging-android-3.0.1.zip](https://github.com/hansemannn/titanium-firebase-cloud-messaging/files/4573670/firebase.cloudmessaging-android-3.0.1.zip)
=> fix(android): fix crash on first app launch, update firebase-messaging to 20.1.6

android/manifest, android/timodule.xml
https://github.com/hansemannn/titanium-firebase-cloud-messaging/issues/130
add missing exported value to make it Android 12 safe
=> fix(android): set exported value

README.md, android/build.gradle, android/local.properties, android/manifest, android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java, android/timodule.xml
* Remove firebase.core as a requirement since it will include AdMob (even if it is not used).
According to Google: https://firebase.google.com/support/release-notes/android it is not needed anymore.
> The Firebase Android library firebase-core is no longer needed. This SDK included the Firebase SDK for Google Analytics.
* Raised the fcm version
> Added methods for determining and controlling whether Google Play services is set as the app’s notification delegate. By default, FCM will now set Google Play services as the app’s notification delegate so that it is allowed to display notifications for the app. This could be used in the future to show an app’s notifications without needing to start the app, which may improve message reliability and timeliness.
Couldn't find any anything in the …
=> feat(android): remove core requirement

android/build.gradle, android/manifest
Minor firebase library update (23.0.0 -> 23.0.7):
* https://firebase.google.com/support/release-notes/android#messaging_v23-0-7 (`This change should reduce the chance of ANRs.`)
* https://firebase.google.com/support/release-notes/android#messaging_v23-0-6 (`Added the POST_NOTIFICATIONS permission to enable posting notifications when targeting SDK level 33`, did the same in the #141 )
* https://firebase.google.com/support/release-notes/android#messaging_v23-0-5
* https://firebase.google.com/support/release-notes/android#messaging_v23-0-3
* https://firebase.google.com/support/release-notes/android#messaging_v23-0-2
* https://firebase.google.com/support/release-notes/android#messaging_v23-0-1
[firebase.cloudmessaging-android-3.3.1.zip](https://github.com/hansemannn/titanium-firebase-cloud-mes …
=> feat(android): minor dep update

android/build.gradle, android/manifest, android/src/firebase/cloudmessaging/CloudMessagingModule.java, android/src/firebase/cloudmessaging/PushHandlerActivity.java, android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java
Since #137 is used in a client project I've merged all the Android PRs into one
<b>Merge PRs</b>
* change intent category (more infos in #137 )
* fix parse bundle error (more infos in #137 )
* update library (more infos in #145)
* fix `toColor` deprecation warning
<b>New:</b>
* use `clearLastData` to clear intent data too. Otherwise it will show up on every resume
[firebase.cloudmessaging-android-3.4.0.zip](https://github.com/hansemannn/titanium-firebase-cloud-messaging/files/11027027/firebase.cloudmessaging-android-3.4.0.zip)
=> feat(android): update library, change intent category, clear data

android/build.gradle, android/manifest
Just a minor version bumb to reflect the announced changes in the FCM infrastructure.
From the current mail:
> Take the following actions before June 20, 2024... Android | >= 23.1.2
No major changes in their changelog:
https://firebase.google.com/support/release-notes/android#messaging_v23-1-2
https://firebase.google.com/support/release-notes/android#messaging_v23-2-1
[firebase.cloudmessaging-android-3.4.1.zip](https://github.com/hansemannn/titanium-firebase-cloud-messaging/files/12305870/firebase.cloudmessaging-android-3.4.1.zip)
23.2.0:
```
Deprecated FCM upstream messaging. After June 21, 2024, API calls to [FirebaseMessaging.send](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessaging#send) in the app won’t trigger upstream messages to the …
```
=> Android version bump

android/manifest, android/src/firebase/cloudmessaging/CloudMessagingModule.java
Looking in my Crashlytics console of my production version, i saw a lot of errors like this on Android 13+:
`Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference(onToken(e):fcm.registerForPushNotifications();:1292)`
When i look for the Titanium code, i see **TiApplication.getAppCurrentActivity()** returns an **Activity**, but on source code from Android, an Activity do not have the _checkSelfPermission_ method on it. 
Searching on google, i found that **Context** have the method implemented.
https://developer.android.com/reference/android/content/Context#checkSelfPermission(java.lang.String)
I tested on my Android 14 device and it works normally to receive tokens and push. …
=> fix: (android) fix checkSelfPermission error on android 13+

android/manifest, android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java
If you click on a notification and read the intent data you'll only get the data node at the moment. This PR will add the normal notification title and body to the fcm_data:
```
intent string extra:  {"custom":"foo","priority":"high","color":"#ff0000","title":"value","channelId":"my_channel3","force_show_in_foreground":"true","notification_title":"My title","notification_body":"My Body"}
```
I've used `notification_title` and `notification_body` in case people already use `title` and `body` in their data fields.
[firebase.cloudmessaging-android-3.4.3.zip](https://github.com/user-attachments/files/17257712/firebase.cloudmessaging-android-3.4.3.zip)
Example app: https://github.com/m1ga/ti.fcm.example
or use
```js
var activity = Ti.Android.currentActivity …
```
=> feat(android): add notification fields to fcm_data

android/manifest, android/src/firebase/cloudmessaging/CloudMessagingModule.java, android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java
This took me a while to figure out - but it allows us to use Braze-related APIs without linking the libraries for users that don't use Braze.
In addition, this PR fixes all warnings.
=> chore(android): be able to call Braze Firebase handler, fix warnings
